In [ ]:
import pandas as pd
from pathlib import Path

In [53]:
DATA_PATH = Path("../data/raw/higher_education.csv")

df = pd.read_csv(
    DATA_PATH,
    sep = ";",
    encoding = "latin-1",
    thousands="."
)

In [45]:
df.head() #visualizamos las primeras 5 filas del dataset

,ANIO,TIPO_UNIV,NIVEL_ACADEM,OF_ACADEM,DISCIP_OCDE,DISCIP_ESPECIF,TIPO_ALUMNO,U_MED,VALOR
0,2014,Privado,Grado,Otros,Ciencias Agrícolas,Ciencias Agropecuarias,EGRESADOS,Cantidad de personas,124
1,2014,Privado,Grado,Otros,Ciencias Agrícolas,Ciencias Agropecuarias,ESTUDIANTES,Cantidad de personas,1475
2,2014,Privado,Grado,Otros,Ciencias Agrícolas,Veterinaria,EGRESADOS,Cantidad de personas,119
3,2014,Privado,Grado,Otros,Ciencias Agrícolas,Veterinaria,ESTUDIANTES,Cantidad de personas,2134
4,2014,Privado,Posgrado,Doctorado,Ciencias Agrícolas,Ciencias Agropecuarias,EGRESADOS,Cantidad de personas,2

In [46]:
df.shape #vemos la cantidad de filas (6074) y columnas (9)

(6074, 9)

In [47]:
df.columns.tolist() #visualizamos las columnas para consultar

['ANIO',
 'TIPO_UNIV',
 'NIVEL_ACADEM',
 'OF_ACADEM',
 'DISCIP_OCDE',
 'DISCIP_ESPECIF',
 'TIPO_ALUMNO',
 'U_MED',
 'VALOR']

In [31]:
# - Buscamos valores únicos para cada columna

In [ ]:
df["ANIO"].unique()

array([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023])

In [32]:
df["TIPO_UNIV"].unique()

<StringArray>
['Privado', 'Pública']
Length: 2, dtype: str

In [40]:
df["NIVEL_ACADEM"].unique()

<StringArray>
['Grado', 'Posgrado', 'Pregrado']
Length: 3, dtype: str

In [33]:
df["OF_ACADEM"].unique()

<StringArray>
['Otros', 'Doctorado', 'Especialidad', 'Maestría']
Length: 4, dtype: str

In [34]:
df["DISCIP_OCDE"].unique()

<StringArray>
[     'Ciencias Agrícolas',        'Ciencias Médicas',
       'Ciencias Sociales',     'Exactas y Naturales',
             'Humanidades', 'Ingeniería y Tecnología']
Length: 6, dtype: str

In [35]:
df["DISCIP_ESPECIF"].unique()

<StringArray>
[                                     'Ciencias Agropecuarias',
                                                 'Veterinaria',
                                       'Bioquímica y Farmacia',
                                                    'Medicina',
                                                 'Odontología',
                     'Paramédicas y Auxiliares de la Medicina',
                                               'Salud Pública',
                                                     'Sanidad',
             'Ciencias de la Información y de la Comunicación',
 'Ciencias Políticas, Relaciones Internacionales y Diplomacia',
                                      'Demografía y Geografía',
                                                     'Derecho',
                                   'Economía y Administración',
                                                   'Educación',
                                    'Otras Ciencias Aplicadas',
                                     'Otras Ciencias Sociales',
                                                  'Psicología',
                  'Sociología, Antropología y Servicio Social',
                                                    'Biología',
                                                      'Física',
                                                  'Industrias',
                                                 'Informática',
                                                  'Matemática',
                                                     'Química',
                                                  'Astronomía',
                                          'Ciencias del Suelo',
                                                 'Estadística',
                                                'Meteorología',
                                                       'Artes',
                                                   'Filosofía',
                                                    'Historia',
                                            'Letras e Idiomas',
                        'Relaciones Institucionales y Humanas',
                                                    'Teología',
                                                 'Arqueología',
                                       'Arquitectura y Diseño',
                                                  'Ingeniería']
Length: 37, dtype: str

In [36]:
df["TIPO_ALUMNO"].unique()

<StringArray>
['EGRESADOS', 'ESTUDIANTES']
Length: 2, dtype: str

In [38]:
df.drop(columns="VALOR").nunique()

ANIO              10
TIPO_UNIV          2
NIVEL_ACADEM       3
OF_ACADEM          4
DISCIP_OCDE        6
DISCIP_ESPECIF    37
TIPO_ALUMNO        2
U_MED              1
dtype: int64

In [ ]:
df.describe(include="all")

,ANIO,TIPO_UNIV,NIVEL_ACADEM,OF_ACADEM,DISCIP_OCDE,DISCIP_ESPECIF,TIPO_ALUMNO,U_MED,VALOR
count,6074.000000,6074,6074,6074,6074,6074,6074,6074,6074.000000
unique,NaN,2,3,4,6,37,2,1,NaN
top,NaN,Pública,Posgrado,Otros,Ciencias Sociales,Informática,EGRESADOS,Cantidad de personas,NaN
freq,NaN,3378,3554,2686,1912,252,3037,6074,NaN
mean,2018.592690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3940.238064
std,2.903075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16632.086988
min,2014.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,2016.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.000000
50%,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.500000
75%,2021.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1116.750000
max,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,240214.000000

In [ ]:
df.duplicated().sum() #no hay filas duplicadas

np.int64(0)